# Activate the Profile for the Correct Provider.
spring:
  profiles:
    active: qa,plaid

# This is where you provider implementation goes to
service:
  implementation:
    package: online.pubudu.framework.service.impl

# Use this to override the Swagger Responses.

swagger:
  tags:
    login-controller:
      - url: /login
        method: POST
        responses:
          - code: 200
            message: new message
            response-class: online.pubudu.framework.service.impl.plaid.dto.LoginResponseDto
          - code: 404
            message: new message
            response-class: online.pubudu.framework.service.impl.plaid.dto.LoginResponseDto
      - url: /login
        method: GET
        responses:
          - code: 200
            message: new message
            response-class: online.pubudu.framework.service.impl.plaid.dto.AccountResponseDto
    account-controller:
      - url: /account
        method: GET
        responses:
          - code: 201
            message: new message
            response-class: online.pubudu.framework.service.impl.plaid.dto.AccountResponseDto